# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e588cd0854d771d49bb74c6c0eb98cf0eb7ad0938fe0e4d22c51efcbd6eca49727e0c9eee145672da99934470c807087ab2517fb0b69a0d8e92311572dc67100
  slack_app : https://ancient-badlands-14496.herokuapp.com/authbegin

test:
  secret_key_base: 1b86c74d42da280ab97af40f025418099087e9c9f305f64c59dea1f9213e4c30a6dc78f37b03b678a584ed65238deb8d51093ba42ec0dc6efef8330d3b01e1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
